spring:
  datasource:
    url: jdbc:h2:file:./db/demodb;DB_CLOSE_ON_EXIT=FALSE
    username: call
    password: test
    driverClassName: org.h2.Driver

logging:
  level:
    root: WARN
    fr.agregio: TRACE