spring:
  datasource:
    url: jdbc:postgresql://localhost/postgresql/call;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: callForTendersApp
    password: 6d65e77fbe8f
    driverClassName: org.PostGreSQL.Driver