spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    mapper:
      accept-case-insensitive-properties: true

server:
  port: ${appPort:8444}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
    tomcat:
      uri-encoding: UTF-8
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html